version: '3.3'
services: #Different containers

  server:
    build: ./server
    ports:
      - "80:80"
    # volumes:
    #   - .:/app
    # networks:
    #   - app-network

  db:
    #image: mysql:5.7
    build: ./db
    #command: --init-file server/script.sql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    #expose:
      # Opens port 3306 on the container
      #- '3306'
      # Where our data will be persisted
    # networks:
    #   - app-network

# Names our volume
# volumes:
#   my-db:

# isloate containers to only communicate with containers on the same network
# networks:
#   app-network:
#     driver: bridge